steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/jinfo:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/jinfo:$COMMIT_SHA
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - jinfo
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/jinfo:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --min-instances=0
      - --max-instances=2
      - --concurrency=40
      - --cpu=1
      - --memory=256Mi
      - --timeout=30s
images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/jinfo:$COMMIT_SHA
substitutions:
  _REGION: asia-northeast1
  _REPOSITORY: rollprojects
options:
  logging: CLOUD_LOGGING_ONLY
